# RaptorFlow Cloud Build
timeout: 1200s

substitutions:
  _REGION: us-central1
  _SERVICE: raptorflow-api

steps:
  - id: build
    name: gcr.io/cloud-builders/docker
    args: [build, -t, gcr.io/$PROJECT_ID/raptorflow:$SHORT_SHA, -t, gcr.io/$PROJECT_ID/raptorflow:latest, .]

  - id: push
    name: gcr.io/cloud-builders/docker
    args: [push, --all-tags, gcr.io/$PROJECT_ID/raptorflow]

  - id: deploy
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE}
      - --image=gcr.io/$PROJECT_ID/raptorflow:$SHORT_SHA
      - --region=${_REGION}
      - --platform=managed
      - --allow-unauthenticated
      - --cpu=2
      - --memory=2Gi
      - --max-instances=10
      - --min-instances=0
      - --timeout=300
      - --set-env-vars=APP_MODE=prod,ENVIRONMENT=production,PORT=8080
      - --set-secrets=OPENAI_API_KEY=openai-api-key:latest,GEMINI_API_KEY=gemini-api-key:latest,OPENROUTER_API_KEY=openrouter-api-key:latest,SUPABASE_URL=supabase-url:latest,SUPABASE_KEY=supabase-key:latest,JWT_SECRET_KEY=jwt-secret:latest,ENCRYPTION_KEY=encryption-key:latest,RAZORPAY_KEY_ID=razorpay-key-id:latest,RAZORPAY_KEY_SECRET=razorpay-key-secret:latest

images:
  - gcr.io/$PROJECT_ID/raptorflow:$SHORT_SHA
  - gcr.io/$PROJECT_ID/raptorflow:latest
