steps:
  # Build backend
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/raptorflow-backend', './backend']
  
  # Build frontend
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/raptorflow-frontend', './frontend']
  
  # Push backend
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/raptorflow-backend']
  
  # Push frontend
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/raptorflow-frontend']
  
  # Deploy backend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'raptorflow-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/raptorflow-backend'
      - '--region'
      - 'asia-south1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'SUPABASE_URL=${_SUPABASE_URL},SUPABASE_KEY=${_SUPABASE_KEY}'
  
  # Deploy frontend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'raptorflow-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/raptorflow-frontend'
      - '--region'
      - 'asia-south1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'NEXT_PUBLIC_API_URL=${_BACKEND_URL}'

images:
  - 'gcr.io/$PROJECT_ID/raptorflow-backend'
  - 'gcr.io/$PROJECT_ID/raptorflow-frontend'
Deployment Script
bash#!/bin/bash
# deploy.sh

set -e

echo " Deploying RaptorFlow ADAPT to Google Cloud..."

# Set project
PROJECT_ID="your-project-id"
gcloud config set project $PROJECT_ID

# Enable required APIs
echo " Enabling APIs..."
gcloud services enable cloudbuild.googleapis.com
gcloud services enable run.googleapis.com
gcloud services enable cloudscheduler.googleapis.com

# Build and deploy
echo "  Building and deploying..."
gcloud builds submit --config=cloudbuild.yaml \
  --substitutions=_SUPABASE_URL=$SUPABASE_URL,_SUPABASE_KEY=$SUPABASE_KEY

# Set up Cloud Scheduler for cron
echo " Setting up trend monitoring cron..."
gcloud scheduler jobs create http trend-monitor-daily \
  --schedule="30 3 * * *" \
  --uri="https://raptorflow-backend-[hash].run.app/api/admin/run-trend-monitor" \
  --http-method=POST \
  --time-zone="Asia/Kolkata"

echo " Deployment complete!"
echo "Backend: https://raptorflow-backend-[hash].run.app"
echo "Frontend: https://raptorflow-frontend-[hash].run.app"
