# Google Cloud Build configuration for RaptorFlow backend and frontend
timeout: 1800s
options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: asia-south1
  _BACKEND_SERVICE: raptorflow-backend
  _FRONTEND_SERVICE: raptorflow-frontend
  _BACKEND_IMAGE: raptorflow-backend
  _FRONTEND_IMAGE: raptorflow-frontend
  _API_BASE_URL: https://api.example.com
  _FRONTEND_BASE_URL: https://app.example.com
  _BACKEND_CPU: "2"
  _BACKEND_MEMORY: 2Gi
  _BACKEND_MAX_INSTANCES: "10"
  _BACKEND_MIN_INSTANCES: "1"
  _BACKEND_LOG_LEVEL: INFO
  _BACKEND_TIMEOUT: "900"
  _FRONTEND_CPU: "1"
  _FRONTEND_MEMORY: 512Mi
  _FRONTEND_MAX_INSTANCES: "5"
  _FRONTEND_MIN_INSTANCES: "1"
  _FRONTEND_TIMEOUT: "300"

steps:
  - id: build-backend
    name: gcr.io/cloud-builders/docker
    dir: backend
    args:
      - build
      - -t
      - gcr.io/$PROJECT_ID/${_BACKEND_IMAGE}:$SHORT_SHA
      - -t
      - gcr.io/$PROJECT_ID/${_BACKEND_IMAGE}:latest
      - .

  - id: build-frontend
    name: gcr.io/cloud-builders/docker
    dir: frontend
    args:
      - build
      - -t
      - gcr.io/$PROJECT_ID/${_FRONTEND_IMAGE}:$SHORT_SHA
      - -t
      - gcr.io/$PROJECT_ID/${_FRONTEND_IMAGE}:latest
      - .

  - id: push-backend-short-sha
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/$PROJECT_ID/${_BACKEND_IMAGE}:$SHORT_SHA

  - id: push-backend-latest
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/$PROJECT_ID/${_BACKEND_IMAGE}:latest

  - id: push-frontend-short-sha
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/$PROJECT_ID/${_FRONTEND_IMAGE}:$SHORT_SHA

  - id: push-frontend-latest
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/$PROJECT_ID/${_FRONTEND_IMAGE}:latest

  - id: deploy-backend
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_BACKEND_SERVICE}
      - --image
      - gcr.io/$PROJECT_ID/${_BACKEND_IMAGE}:$SHORT_SHA
      - --region
      - ${_REGION}
      - --platform
      - managed
      - --allow-unauthenticated
      - --cpu
      - ${_BACKEND_CPU}
      - --memory
      - ${_BACKEND_MEMORY}
      - --max-instances
      - ${_BACKEND_MAX_INSTANCES}
      - --min-instances
      - ${_BACKEND_MIN_INSTANCES}
      - --timeout
      - ${_BACKEND_TIMEOUT}
      - --set-env-vars
      - ENVIRONMENT=production,LOG_LEVEL=${_BACKEND_LOG_LEVEL},API_URL=${_API_BASE_URL},FRONTEND_URL=${_FRONTEND_BASE_URL},ALLOWED_ORIGINS=${_FRONTEND_BASE_URL}
      - --set-secrets
      - SUPABASE_URL=supabase-url:latest,SUPABASE_SERVICE_KEY=supabase-service-key:latest,SUPABASE_KEY=supabase-key:latest,SUPABASE_ANON_KEY=supabase-key:latest,OPENAI_API_KEY=openai-api-key:latest,GEMINI_API_KEY=gemini-api-key:latest,PERPLEXITY_API_KEY=perplexity-api-key:latest,GOOGLE_API_KEY=google-api-key:latest,RAZORPAY_KEY_ID=razorpay-key-id:latest,RAZORPAY_KEY_SECRET=razorpay-key-secret:latest,RAZORPAY_WEBHOOK_SECRET=razorpay-webhook-secret:latest,JWT_SECRET=jwt-secret:latest,JWT_SECRET_KEY=jwt-secret:latest,DATABASE_URL=database-url:latest,REDIS_URL=redis-url:latest,SENTRY_DSN=sentry-dsn:latest,ENCRYPTION_KEY=encryption-key:latest

  - id: deploy-frontend
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_FRONTEND_SERVICE}
      - --image
      - gcr.io/$PROJECT_ID/${_FRONTEND_IMAGE}:$SHORT_SHA
      - --region
      - ${_REGION}
      - --platform
      - managed
      - --allow-unauthenticated
      - --cpu
      - ${_FRONTEND_CPU}
      - --memory
      - ${_FRONTEND_MEMORY}
      - --max-instances
      - ${_FRONTEND_MAX_INSTANCES}
      - --min-instances
      - ${_FRONTEND_MIN_INSTANCES}
      - --timeout
      - ${_FRONTEND_TIMEOUT}
      - --set-env-vars
      - NEXT_PUBLIC_API_URL=${_API_BASE_URL},NODE_ENV=production

images:
  - gcr.io/$PROJECT_ID/${_BACKEND_IMAGE}:$SHORT_SHA
  - gcr.io/$PROJECT_ID/${_BACKEND_IMAGE}:latest
  - gcr.io/$PROJECT_ID/${_FRONTEND_IMAGE}:$SHORT_SHA
  - gcr.io/$PROJECT_ID/${_FRONTEND_IMAGE}:latest
