version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: raptorflow-backend
    ports:
      - "8000:8080"
    env_file:
      - .env
    environment:
      - PORT=8080
      - APP_MODE=${APP_MODE:-prod}
      - ENVIRONMENT=development
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    volumes:
      - ./backend:/app:ro
    networks:
      - raptorflow
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: raptorflow-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    depends_on:
      backend:
        condition: service_healthy
    volumes:
      - ./frontend:/app:ro
    networks:
      - raptorflow
    restart: unless-stopped

networks:
  raptorflow:
    driver: bridge
